(()=>{
'use strict';
// ===== 調整値（仮） =====

// 得点: (消去数-2)^2 * 10 / 減点: 残数*(10+残数)

const $=id=>document.getElementById(id); const pages=["Top","Settings","Room","Lobby","Game","Spectate","Result"];
function show(p){pages.forEach(x=>$("page"+x).classList.toggle("hidden",x!==p));}
function toast(s){$("toast").textContent=s;}
const K={name:"sg_player_name",avatar:"sg_player_avatar",bgm:"sg_bgm",se:"sg_se",bgmPrev:"sg_bgm_prev",sePrev:"sg_se_prev",best:"sg_best"};
function getName(){return (localStorage.getItem(K.name)||"Player").trim().slice(0,16)||"Player"} function getAvatar(){return localStorage.getItem(K.avatar)||""}
function initials(n){return Array.from(n||"?").slice(0,2).join("")}
function avatarHTML(name,av,cls="avatar"){return `<div class="${cls}">${av?`<img src="${av}" alt="">`:initials(name)}</div>`}
function syncTopProfile(){$("topProfile").innerHTML=avatarHTML(getName(),getAvatar())+`<div><div class="tiny">PLAYER</div><div class="profileName">${esc(getName())}</div></div>`}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]))}
function setupSettings(){
 $("nameInput").value=getName()==="Player"?"":getName(); renderAvatarPreview();
 const bg=+(localStorage.getItem(K.bgm)??70),se=+(localStorage.getItem(K.se)??80); $("bgmRange").value=bg;$("seRange").value=se;syncSound("bgm");syncSound("se");
}
function renderAvatarPreview(){$("avatarPreview").innerHTML=getAvatar()?`<img src="${getAvatar()}" alt="">`:initials(getName())}
function syncSound(kind){const r=$(kind+"Range"),v=+r.value;localStorage.setItem(K[kind],v);if(v>0)localStorage.setItem(K[kind+"Prev"],v);$(kind+"Val").textContent=v+"%";$(kind+"Mute").textContent=v===0?"🔇":"🔊"}
function toggleMute(kind){const r=$(kind+"Range");if(+r.value===0){r.value=+(localStorage.getItem(K[kind+"Prev"])||70)}else{localStorage.setItem(K[kind+"Prev"],r.value);r.value=0}syncSound(kind)}
async function makeAvatar(file){if(!file||!file.type.startsWith("image/"))throw Error("画像ファイルを選択してください");const url=URL.createObjectURL(file);const img=new Image();await new Promise((res,rej)=>{img.onload=res;img.onerror=rej;img.src=url});URL.revokeObjectURL(url);const side=Math.min(img.naturalWidth,img.naturalHeight),sx=(img.naturalWidth-side)/2,sy=(img.naturalHeight-side)/2;const c=document.createElement("canvas");c.width=c.height=128;c.getContext("2d").drawImage(img,sx,sy,side,side,0,0,128,128);return c.toDataURL("image/webp",.72)}

// ===== seeded board =====
function xmur3(str){let h=1779033703^str.length;for(let i=0;i<str.length;i++){h=Math.imul(h^str.charCodeAt(i),3432918353);h=h<<13|h>>>19}return()=>{h=Math.imul(h^h>>>16,2246822507);h=Math.imul(h^h>>>13,3266489909);return(h^h>>>16)>>>0}}
function mulberry32(a){return()=>{let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function rngFor(seed,index){return mulberry32(xmur3(seed+":"+index)())}
function generateBoard(seed,index){const r=rngFor(seed,index),b=[];for(let y=0;y<CFG.ROWS;y++){b[y]=[];for(let x=0;x<CFG.COLS;x++)b[y][x]=Math.floor(r()*CFG.COLORS)}return b}
function generateMission(seed,index,board){const r=rngFor(seed+":mission",index);const totals=Array(CFG.COLORS).fill(0);board.flat().forEach(v=>totals[v]++);const color=Math.floor(r()*CFG.COLORS);const max=Math.max(5,Math.min(14,totals[color]-1));const count=Math.max(5,Math.floor(5+r()*(max-4)));return{color,count,bonus:CFG.MISSION_BONUS_BASE+Math.max(0,count-5)*50,done:false}}
function cloneBoard(b){return b.map(r=>r.slice())}
function groupAt(b,sy,sx){const v=b[sy]?.[sx];if(v==null)return[];const q=[[sy,sx]],seen=new Set([sy+","+sx]),out=[];while(q.length){const [y,x]=q.shift();out.push([y,x]);for(const [dy,dx] of [[1,0],[-1,0],[0,1],[0,-1]]){const ny=y+dy,nx=x+dx,k=ny+","+nx;if(ny>=0&&ny<CFG.ROWS&&nx>=0&&nx<CFG.COLS&&!seen.has(k)&&b[ny][nx]===v){seen.add(k);q.push([ny,nx])}}}return out}
function hasMove(b){for(let y=0;y<CFG.ROWS;y++)for(let x=0;x<CFG.COLS;x++)if(b[y][x]!=null&&groupAt(b,y,x).length>=2)return true;return false}
function remaining(b){return b.flat().filter(v=>v!=null).length}
function collapse(b){for(let x=0;x<CFG.COLS;x++){const vals=[];for(let y=CFG.ROWS-1;y>=0;y--)if(b[y][x]!=null)vals.push(b[y][x]);for(let y=CFG.ROWS-1,i=0;y>=0;y--)b[y][x]=i<vals.length?vals[i++]:null}const cols=[];for(let x=0;x<CFG.COLS;x++){let any=false;for(let y=0;y<CFG.ROWS;y++)if(b[y][x]!=null){any=true;break}if(any)cols.push(x)}const nb=Array.from({length:CFG.ROWS},()=>Array(CFG.COLS).fill(null));cols.forEach((old,nx)=>{for(let y=0;y<CFG.ROWS;y++)nb[y][nx]=b[y][old]});for(let y=0;y<CFG.ROWS;y++)for(let x=0;x<CFG.COLS;x++)b[y][x]=nb[y][x]}
function scoreFor(n){return Math.max(0,(n-2)*(n-2)*CFG.SCORE_UNIT)} function penaltyFor(n){return n*(CFG.PENALTY_BASE+n)}
const colorNames=["赤","青","緑","黄","紫"];

let mode="single",seed="",boardIndex=1,board=[],mission=null,score=0,selected=[],startAt=0,timerId=null,finished=false,currentRoomKey="",currentRoom=null,myUid="",roomUnsub=null,spectating=false,spectateFocus="";
function renderBoard(el,b,mini=false,clickable=false){el.innerHTML="";for(let y=0;y<CFG.ROWS;y++)for(let x=0;x<CFG.COLS;x++){const v=b?.[y]?.[x]??null;const d=document.createElement(clickable?"button":"div");d.className=(mini?"miniCell ":"cell ")+(v==null?"empty":"c"+v);if(!mini&&selected.some(([a,c])=>a===y&&c===x))d.classList.add("sel");if(clickable&&v!=null){d.type="button";d.dataset.y=y;d.dataset.x=x;d.addEventListener("click",cellClick)}el.appendChild(d)}}
function missionText(m){return m?`ミッション：${colorNames[m.color]}を${m.count}個以上同時に消す　+${m.bonus}点${m.done?"　✓達成":""}`:""}
function renderGame(){renderBoard($("mainBoard"),board,false,true);$("scoreEl").textContent=score.toLocaleString();$("boardIndexEl").textContent=`第${boardIndex}盤面`;$("missionEl").textContent=missionText(mission);$("missionEl").classList.toggle("done",!!mission?.done);if(mode==="single")$("bestEl").textContent=`BEST ${(+(localStorage.getItem(K.best)||0)).toLocaleString()}`;else $("bestEl").textContent="";checkStuck(); if(mode==="multi")pushState()}
function cellClick(e){if(finished)return;const y=+e.currentTarget.dataset.y,x=+e.currentTarget.dataset.x,g=groupAt(board,y,x);if(g.length<2){selected=[];$("boardNote").textContent="2個以上つながった色を選択";renderBoard($("mainBoard"),board,false,true);return}const same=selected.length===g.length&&g.every(([a,b])=>selected.some(([c,d])=>a===c&&b===d));if(!same){selected=g;$("boardNote").textContent=`${g.length}個選択　もう一度タップで消去（+${scoreFor(g.length)}点）`;renderBoard($("mainBoard"),board,false,true);return}const color=board[y][x];g.forEach(([a,b])=>board[a][b]=null);score+=scoreFor(g.length);if(!mission.done&&color===mission.color&&g.length>=mission.count){mission.done=true;score+=mission.bonus;toast(`ミッション達成 +${mission.bonus}点`)}collapse(board);selected=[];$("boardNote").textContent=`${g.length}個消去`;renderGame()}
function checkStuck(){const rem=remaining(board),stuck=rem===0||!hasMove(board);$("nextBoardBtn").classList.toggle("hidden",!stuck||finished);if(stuck&&!finished){const pen=penaltyFor(rem);$("nextBoardBtn").textContent=`次の盤面へ（残ブロック減点 ${pen===0?"0":"-"+pen}点）`;$("boardNote").textContent=rem===0?"全消し！ 次の盤面へ進めます":`消せる組み合わせなし：残り${rem}個`}}
function nextBoard(){if(finished)return;const rem=remaining(board);score=Math.max(0,score-penaltyFor(rem));boardIndex++;board=generateBoard(seed,boardIndex);mission=generateMission(seed,boardIndex,board);selected=[];renderGame();toast(`第${boardIndex}盤面へ`)}
function startGame(opts){mode=opts.mode;seed=opts.seed||crypto.randomUUID();boardIndex=opts.boardIndex||1;board=generateBoard(seed,boardIndex);mission=generateMission(seed,boardIndex,board);score=0;selected=[];finished=false;startAt=opts.startAt||Date.now();show("Game");$("gameModeLabel").textContent=mode==="single"?"SINGLE":"MULTI";$("gamePlayerName").textContent=getName();$("opponentArea").classList.toggle("hidden",mode!=="multi");renderGame();clearInterval(timerId);timerId=setInterval(tick,250);tick()}
function tick(){const left=Math.max(0,CFG.TIME_LIMIT_SEC-Math.floor((Date.now()-startAt)/1000));$("timerEl").textContent=`${Math.floor(left/60)}:${String(left%60).padStart(2,"0")}`;if(left<=0)finishPlayer()}
function finishPlayer(){if(finished)return;finished=true;clearInterval(timerId);selected=[];$("nextBoardBtn").classList.add("hidden");$("boardNote").textContent="タイムアップ / 集計待ち";if(mode==="single"){const best=+(localStorage.getItem(K.best)||0);if(score>best)localStorage.setItem(K.best,score);showResult([{name:getName(),avatar:getAvatar(),score,status:"完了"}])}else{firebase.database().ref(`rooms/${currentRoomKey}/players/${myUid}`).update({score,finished:true,status:"集計待ち",board,boardIndex,mission,updatedAt:firebase.database.ServerValue.TIMESTAMP})}}

// ===== Firebase multi =====
let fbReady=false; async function initFirebase(){try{if(!firebase.apps.length)firebase.initializeApp(firebaseConfig);const cred=await firebase.auth().signInAnonymously();myUid=cred.user.uid;fbReady=true;$("onlineStatus").textContent="オンライン";$("onlineStatus").className="status ok";toast("準備完了")}catch(e){console.error(e);$("onlineStatus").textContent="Firebase接続失敗";$("onlineStatus").className="status warn";toast("オンライン機能に接続できません")}}
async function passHash(s){const data=new TextEncoder().encode(s);const h=await crypto.subtle.digest("SHA-256",data);return Array.from(new Uint8Array(h)).map(b=>b.toString(16).padStart(2,"0")).join("")}
function validPass(s){const a=Array.from(s);if(a.length<1||a.length>8)return false;return /^[A-Za-z0-9@._+\-/\u3040-\u309F\u30A0-\u30FF\u3400-\u4DBF\u4E00-\u9FFF]+$/u.test(s)}
function playerData(){return{name:getName(),avatar:getAvatar(),score:0,finished:false,status:"ゲーム中",board:null,boardIndex:1,mission:null,joinedAt:firebase.database.ServerValue.TIMESTAMP}}
async function createRoom(pass){if(!fbReady)throw Error("オンライン未接続");const key=await passHash(pass);const ref=firebase.database().ref(`rooms/${key}`);const snap=await ref.once("value");if(snap.exists())throw Error("同じ合言葉のルームが使用中です");const s=crypto.randomUUID();await ref.set({version:1,status:"waiting",hostUid:myUid,seed:s,timeLimit:CFG.TIME_LIMIT_SEC,createdAt:firebase.database.ServerValue.TIMESTAMP,players:{[myUid]:playerData()}});enterLobby(key,pass)}
async function findRoom(pass){const key=await passHash(pass),snap=await firebase.database().ref(`rooms/${key}`).once("value");if(!snap.exists())throw Error("ルームが見つかりません");return{key,data:snap.val()}}
async function joinRoom(key){const ref=firebase.database().ref(`rooms/${key}`);const snap=await ref.once("value"),r=snap.val();if(!r||r.status!=="waiting")throw Error("参加受付中ではありません");const count=Object.keys(r.players||{}).length;if(count>=2)throw Error("参加枠が埋まっています。観戦してください");await ref.child(`players/${myUid}`).set(playerData());enterLobby(key,"")}
function enterLobby(key,pass){currentRoomKey=key;show("Lobby");$("lobbyPass").textContent=pass||"参加済み";subscribeRoom();}
function subscribeRoom(){if(roomUnsub){roomUnsub();roomUnsub=null}const ref=firebase.database().ref(`rooms/${currentRoomKey}`);const cb=s=>{const r=s.val();if(!r){toast("ルームが終了しました");show("Top");return}currentRoom=r;renderLobby(r);if(spectating){renderSpectate(r);if(r.status==="result")showSharedResult(r)}else if(r.status==="playing"&&!finished&&mode!=="multi"){startGame({mode:"multi",seed:r.seed,startAt:r.startAt})} if(r.status==="result")showSharedResult(r)};ref.on("value",cb);roomUnsub=()=>ref.off("value",cb)}
function renderLobby(r){const ps=Object.entries(r.players||{});$("lobbyState").textContent=r.status==="waiting"?"参加者を待っています":r.status;$("lobbyPlayers").innerHTML=ps.map(([uid,p])=>`<div class="playerRow">${avatarHTML(p.name,p.avatar)}<div class="grow"><b>${esc(p.name)}</b><div class="tiny">${uid===r.hostUid?"ホスト":"参加者"}</div></div></div>`).join("");const host=r.hostUid===myUid;$("startMatch").classList.toggle("hidden",!host||ps.length<2||r.status!=="waiting")}
async function startMatch(){const startAt=Date.now()+3000;await firebase.database().ref(`rooms/${currentRoomKey}`).update({status:"playing",startAt});mode="none";toast("3秒後に開始")}
async function pushState(){if(!currentRoomKey||!myUid||mode!=="multi")return;firebase.database().ref(`rooms/${currentRoomKey}/players/${myUid}`).update({score,board,boardIndex,mission,finished:false,status:"ゲーム中",updatedAt:firebase.database.ServerValue.TIMESTAMP}).catch(()=>{}) ;renderOpponent()}
function renderOpponent(){const r=currentRoom;if(!r)return;const other=Object.entries(r.players||{}).find(([uid])=>uid!==myUid);if(!other){$("opponentArea").classList.add("hidden");return}$("opponentArea").classList.remove("hidden");const p=other[1];renderBoard($("opponentBoard"),p.board||generateBoard(r.seed,p.boardIndex||1),true,false);$("opponentMeta").innerHTML=avatarHTML(p.name,p.avatar)+`<div><b>${esc(p.name)}</b><div class="tiny">${esc(p.status||"ゲーム中")}</div></div><div class="oppScore">${(+p.score||0).toLocaleString()}点</div>`}
async function maybeFinalize(r){if(!r||r.status!=="playing")return;const ps=Object.values(r.players||{});if(ps.length>=2&&ps.every(p=>p.finished)){await firebase.database().ref(`rooms/${currentRoomKey}`).update({status:"result",resultAt:firebase.database.ServerValue.TIMESTAMP})}}
function showSharedResult(r){clearInterval(timerId);const arr=Object.values(r.players||{}).map(p=>({name:p.name,avatar:p.avatar,score:+p.score||0,status:p.status||"完了"})).sort((a,b)=>b.score-a.score);showResult(arr)}
function showResult(arr){show("Result");$("resultRows").innerHTML=arr.map((p,i)=>`<div class="resultRow">${avatarHTML(p.name,p.avatar)}<div><b>${i+1}位 ${esc(p.name)}</b><div class="badge">${esc(p.status||"")}</div></div><div style="font-weight:1000">${p.score.toLocaleString()}点</div></div>`).join("")}

// watch global room and finalize / opponent
setInterval(()=>{if(currentRoom&&currentRoom.status==="playing"){renderOpponent();maybeFinalize(currentRoom)}},500);

function startSpectate(key){currentRoomKey=key;spectating=true;show("Spectate");subscribeRoom();}
function renderSpectate(r){const entries=Object.entries(r.players||{});if(!entries.length)return;if(!spectateFocus||!r.players[spectateFocus])spectateFocus=entries[0][0];const fp=r.players[spectateFocus];$("spectateMission").textContent=missionText(fp.mission||generateMission(r.seed,fp.boardIndex||1,generateBoard(r.seed,fp.boardIndex||1)));$("spectateBigMeta").innerHTML=avatarHTML(fp.name,fp.avatar)+`<div><b>${esc(fp.name)}</b><div class="tiny">${esc(fp.status||"ゲーム中")}</div></div><div class="oppScore">${(+fp.score||0).toLocaleString()}点</div>`;renderBoard($("spectateBigBoard"),fp.board||generateBoard(r.seed,fp.boardIndex||1),false,false);$("spectateGrid").innerHTML="";entries.forEach(([uid,p])=>{const box=document.createElement("button");box.type="button";box.className="spectateMini";box.style.color="inherit";box.innerHTML=`<div class="tiny">${esc(p.name)} / ${(+p.score||0).toLocaleString()}点</div><div class="miniBoard"></div>`;renderBoard(box.querySelector(".miniBoard"),p.board||generateBoard(r.seed,p.boardIndex||1),true,false);box.addEventListener("click",()=>{spectateFocus=uid;renderSpectate(r)});$("spectateGrid").appendChild(box)})}
async function leaveRoom(){if(currentRoomKey&&myUid&&!spectating){try{await firebase.database().ref(`rooms/${currentRoomKey}/players/${myUid}`).remove();const snap=await firebase.database().ref(`rooms/${currentRoomKey}/players`).once("value");if(!snap.exists())await firebase.database().ref(`rooms/${currentRoomKey}`).remove()}catch(e){}}cleanupRoom();show("Top")}
function cleanupRoom(){if(roomUnsub){roomUnsub();roomUnsub=null}currentRoomKey="";currentRoom=null;spectating=false;spectateFocus="";mode="single";finished=false;clearInterval(timerId)}

// ===== UI bindings =====
$("singleBtn").onclick=()=>startGame({mode:"single",seed:crypto.randomUUID(),startAt:Date.now()});
let roomIntent="create",foundRoom=null;
$("createBtn").onclick=()=>{roomIntent="create";foundRoom=null;$("roomTitle").textContent="ルーム作成";$("roomPrompt").textContent="合言葉を設定してください。";$("roomAction").textContent="ルーム作成";$("roomFound").classList.add("hidden");$("passInput").value="";show("Room")};
$("joinBtn").onclick=()=>{roomIntent="join";foundRoom=null;$("roomTitle").textContent="ルーム参加";$("roomPrompt").textContent="合言葉を入力してルームを検索します。";$("roomAction").textContent="検索";$("roomFound").classList.add("hidden");$("passInput").value="";show("Room")};
$("roomAction").onclick=async()=>{const p=$("passInput").value;if(!validPass(p)){toast("合言葉は1〜8文字。絵文字・空白・未許可記号は使えません");return}try{if(roomIntent==="create")await createRoom(p);else{foundRoom=await findRoom(p);$("roomFound").classList.remove("hidden");toast("ルームが見つかりました")}}catch(e){toast(e.message||String(e))}};
$("participateBtn").onclick=async()=>{try{await joinRoom(foundRoom.key)}catch(e){toast(e.message)}};$("spectateBtn").onclick=()=>startSpectate(foundRoom.key);
$("settingsBtn").onclick=()=>{setupSettings();show("Settings")};document.querySelectorAll("[data-back]").forEach(b=>b.onclick=()=>{show("Top");syncTopProfile()});
$("nameInput").addEventListener("input",()=>{const n=$("nameInput").value.trim().slice(0,16);if(n)localStorage.setItem(K.name,n);else localStorage.removeItem(K.name);renderAvatarPreview();syncTopProfile()});
$("avatarInput").onchange=async()=>{try{const f=$("avatarInput").files[0];if(!f)return;localStorage.setItem(K.avatar,await makeAvatar(f));renderAvatarPreview();syncTopProfile();toast("アイコンを保存しました")}catch(e){toast("画像処理に失敗しました")}};$("avatarRemove").onclick=()=>{localStorage.removeItem(K.avatar);renderAvatarPreview();syncTopProfile()};
for(const k of ["bgm","se"]){$(k+"Range").addEventListener("input",()=>syncSound(k));$(k+"Mute").onclick=()=>toggleMute(k)}$("creditBtn").onclick=()=>$("creditBox").classList.toggle("hidden");
$("nextBoardBtn").onclick=nextBoard;$("startMatch").onclick=startMatch;$("leaveLobby").onclick=leaveRoom;$("leaveSpectate").onclick=()=>{cleanupRoom();show("Top")};$("quitGame").onclick=()=>{if(mode==="multi")finishPlayer();else{clearInterval(timerId);show("Top")}};$("resultTop").onclick=async()=>{if(currentRoomKey&&!spectating){try{await firebase.database().ref(`rooms/${currentRoomKey}/players/${myUid}`).remove()}catch(e){}}cleanupRoom();show("Top")};

syncTopProfile();initFirebase();
})();
